virtualmachines:
  hosts: 
    lyes02:
      ansible_host: root@192.168.100.2
    lyes03:
      ansible_host: root@192.168.100.3
    lyes04:
      ansible_host: root@192.168.100.4
    lyes05:
      ansible_host: root@192.168.100.5