- name: Mon prmemier play
  hosts : lyes02
  remote_user: root
  become: true
  tasks:
    - name: Nom de la tasks
      ansible.builtin.raw: 'sudo apt install python3'
      args:
        executable: /bin/bash
    
    - name: Copier conf
      copy:
        src: dockerfile_ansible
        dest: ~/testinho
        mode: "0777"
