- name: Mon prmemier play
  hosts : lyesmachines
  remote_user: root
  gather_facts: true
  strategy: free
  order: inventory
  tasks: 
    - name: Ping hosts
      ansible.builtin.ping: ~

    - name: apt update cache
      tags: update
      ansible.builtin.apt: 
        update_cache: true